sonar.projectKey=sports-center-management-system-uat-fe
sonar.projectName=Sports Center Management System UAT FE
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/test-results/**,**/playwright-report/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,tests/**
sonar.sourceEncoding=UTF-8